const SET_AUTH_LOADING = 'SET_AUTH_LOADING'
const SET_AUTH_ADMIN = 'SET_AUTH_ADMIN'
const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
const SET_AUTH_LOGOUT = 'SET_AUTH_LOGOUT'

const SET_SEARCH_SUGGESTIONS_LOADING = 'SET_SEARCH_SUGGESTIONS_LOADING'
const SET_SEARCH_SUGGESTIONS = 'SET_SEARCH_SUGGESTIONS'
const SET_SEARCH_SUGGESTIONS_ERROR = 'SET_SEARCH_SUGGESTIONS_ERROR'
const SET_SEARCH_RESULTS_LOADING = 'SET_SEARCH_RESULTS_LOADING'
const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
const SET_SEARCH_RESULTS_ERROR = 'SET_SEARCH_RESULTS_ERROR'

const SET_LATEST_POSTS_LOADING = 'SET_LATEST_POSTS_LOADING'
const SET_LATEST_POSTS = 'SET_LATEST_POSTS'
const SET_LATEST_POSTS_ERROR = 'SET_LATEST_POSTS_ERROR'

const SET_POSTS_LOADING = 'SET_POSTS_LOADING'
const SET_POSTS = 'SET_POSTS'
const SET_POSTS_ERROR = 'SET_POSTS_ERROR'

const SET_PUBLISHED_STATUS_ALL_BLOGS = 'SET_PUBLISHED_STATUS'
const SET_PUBLISHED_STATUS_SEARCH_PAGE = 'SET_PUBLISHED_STATUS_SEARCH_PAGE'

const SET_SINGLE_POST_LOADING = 'SET_SINGLE_POST_LOADING'
const SET_SINGLE_POST = 'SET_SINGLE_POST'
const SET_SINGLE_POST_ERROR = 'SET_SINGLE_POST_ERROR'
const SET_PUBLISHED_STATUS_SINGLE_POST = 'SET_PUBLISHED_STATUS_SINGLE_POST'

module.exports = {
  SET_AUTH_LOADING,
  SET_AUTH_ADMIN,
  SET_AUTH_ERROR,
  SET_AUTH_LOGOUT,
  SET_SEARCH_SUGGESTIONS_LOADING,
  SET_SEARCH_SUGGESTIONS,
  SET_SEARCH_SUGGESTIONS_ERROR,
  SET_SEARCH_RESULTS_LOADING,
  SET_SEARCH_RESULTS,
  SET_SEARCH_RESULTS_ERROR,
  SET_LATEST_POSTS_LOADING,
  SET_LATEST_POSTS,
  SET_LATEST_POSTS_ERROR,
  SET_POSTS_LOADING,
  SET_POSTS,
  SET_POSTS_ERROR,
  SET_PUBLISHED_STATUS_ALL_BLOGS,
  SET_PUBLISHED_STATUS_SEARCH_PAGE,
  SET_PUBLISHED_STATUS_SINGLE_POST,
  SET_SINGLE_POST_ERROR,
  SET_SINGLE_POST,
  SET_SINGLE_POST_LOADING
}
